name: Show the secrets 

on:
  workflow_dispatch:

jobs:
  show-secrts:
    runs-on: ubuntu-latest
    steps:
      - name: Attempt to expose a secret
        run: echo "${{secrets.curso_actions_secret}}" 
      
      - name: Attempt to expose a secret by manipulating the output
        run: echo "${{secrets.curso_actions_secret}}" | sed 's/./&'