name: Criando nosso trigger pull_request

on:
  pull_request:
    types: [opened, edited, closed,reopened]
    branches:
      - 'main'
      - 'main*'
      - 'main/** '

jobs:
  jobs-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Printa pull_request        
        run: echo "Uma pull_request foi aberta/editada/deletada/reaberta com destino a branch main"