name: Testando o trigger do tipo create
on:
  create
jobs:
  print-modification:
    runs-on: ubuntu-latest
    steps:

      - name: Avisa a modificacao
        run: echo "Este workflow foi trigado, pois uma regra de Branch Protection rule foi adicionada"