name: Criando nosso trigger Schedule
on:
  schedule:
    - cron: '41 14 * * 4'

jobs:
  executa-schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Informa Horário       
        run: echo "Schedule executado com sucesso, agora são $(date) UTC"